### ISSUE TITLE
Off-topic: Great project! Are you open to collaboration?

### ISSUE THREAD

**Issue by ux-git** [chessurisme/faux-s-140#4]
Hey dear brother! Sorry for creating this issue, I couldn't find a way to reach you out, but I really like your project and your enthusiasm in building it!

Are you open to collaborating on a theocratic open-source project? If so, please let me know. Looking forward to hearing from you!

**Comment by chessurisme** [comment]
Hi, brother, I'll take time to think of this. BTW, you can email with this: chessurisme@gmail.com. My schedule is currently full, and I'm out of ministry til Sunday starting tomorrow, Friday. Monday will be cleaning day. Please be patience, I heart warmly regard your participation, just wait for my decision.
